// Command codexreview manages an OpenAI Codex (`codex` CLI) code review end to end:
// it invokes codex in a way that CANNOT hang, captures stdout/stderr, detects the
// real failure modes (quota/auth/empty), parses the ACK/NAK verdict, renders a
// PR comment from a Go template, and posts it with `gh`.
//
// Why a tool instead of a shell one-liner: `codex exec` blocks FOREVER if its stdin
// is left open (it waits to "read additional input from stdin"); a piped
// `codex exec ... | tail` hangs exactly this way. An exec.Cmd with Stdin == nil
// connects the child to /dev/null, so the hang is structurally impossible — and a
// hard context timeout + process-group kill is the backstop.
//
// Subcommands:
//
//	codexreview review  --base <branch|sha>   [flags]   # diff review of a branch/range
//	codexreview exec    --prompt "<steer>"    [flags]   # steered analysis (review can't take a prompt)
//
// Common flags: --model, --effort, --timeout, --post, --pr, --repo, --bypass-sandbox, --skill-url, --dir.
package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
	"text/template"
	"time"
)

const defaultSkillURL = "https://github.com/birdayz/skills/tree/master/codex-review"

// commentTmpl is the PR-comment template — the same shape the skill documents, but
// rendered from data instead of an unquoted printf. Kept overridable via --template.
const commentTmpl = "**Codex {{.Kind}}{{with .Duration}} in {{.}}{{end}}** · `{{.SHA}}`\n\n" +
	"---\n\n{{.Review}}\n\n---\n\n" +
	"Generated by Codex {{.Version}} on {{.Model}} ({{.Effort}}) and [codex-review]({{.SkillURL}})"

// quotaRE matches the stderr signatures of a non-error EMPTY run: an exit-0 codex
// that produced no verdict because it was rate-limited, unauthenticated, or errored
// mid-stream. An empty review is NEVER a clean pass.
var quotaRE = regexp.MustCompile(`(?i)rate.?limit|quota|usage limit|429|too many|reached|not logged in|unauthor|stream error|error:|ContextWindowExceeded|UsageLimitExceeded`)

// verdictRE pulls a trailing ACK / NAK / LGTM verdict out of the review prose.
var verdictRE = regexp.MustCompile(`(?i)\b(ACK|NAK|LGTM)\b`)

type config struct {
	mode     string // "review" | "exec"
	base     string
	commit   string
	prompt   string
	model    string
	effort   string
	timeout  time.Duration
	post     bool
	pr       string
	repo     string
	bypass   bool
	skillURL string
	dir      string
	tmplFile string
	codexBin string
	ghBin    string
}

func main() {
	if len(os.Args) < 2 {
		fail("usage: codexreview <review|exec> [flags]; run with -h for flags")
	}
	cfg := parseFlags(os.Args[1], os.Args[2:])

	// One Ctrl-C cleanly cancels the run (kills the whole codex process group).
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	res, err := run(ctx, cfg)
	if err != nil {
		fail("%v", err)
	}

	// Always surface the verdict + scratch paths for the caller.
	fmt.Printf("VERDICT: %s\n", res.Verdict)
	fmt.Printf("review: %s  (%d lines, %s)\n", res.ReviewPath, countLines(res.Review), res.Duration)
	if res.Posted != "" {
		fmt.Printf("posted: %s\n", res.Posted)
	}
	// Echo the review prose so the caller (an agent) reads it inline.
	fmt.Printf("\n----- review -----\n%s\n", strings.TrimSpace(res.Review))
}

func parseFlags(mode string, args []string) config {
	if mode != "review" && mode != "exec" {
		fail("first arg must be 'review' or 'exec', got %q", mode)
	}
	fs := flag.NewFlagSet("codexreview "+mode, flag.ExitOnError)
	cfg := config{mode: mode}
	fs.StringVar(&cfg.base, "base", "", "review: base branch/sha to diff against (review mode; default = PR base or repo default)")
	fs.StringVar(&cfg.commit, "commit", "", "review: review a single commit instead of a range")
	fs.StringVar(&cfg.prompt, "prompt", "", "exec: the steering prompt (exec mode, required)")
	fs.StringVar(&cfg.model, "model", env("CODEX_REVIEW_MODEL", "gpt-5.5"), "codex model (-m)")
	fs.StringVar(&cfg.effort, "effort", env("CODEX_REVIEW_REASONING_EFFORT", "xhigh"), "reasoning effort (-c model_reasoning_effort=)")
	fs.DurationVar(&cfg.timeout, "timeout", 25*time.Minute, "hard wall-clock cap; the run is killed (process group) if exceeded")
	fs.BoolVar(&cfg.post, "post", false, "post the review as a PR comment via gh")
	fs.StringVar(&cfg.pr, "pr", "", "PR number to post to (default: the current branch's PR)")
	fs.StringVar(&cfg.repo, "repo", "", "owner/name for gh (default: inferred from cwd)")
	fs.BoolVar(&cfg.bypass, "bypass-sandbox", false, "use --dangerously-bypass-approvals-and-sandbox instead of -s read-only (for NESTED sandboxes where bwrap can't nest; review writes nothing, so no edit risk)")
	fs.StringVar(&cfg.skillURL, "skill-url", defaultSkillURL, "skill URL for the comment footer")
	fs.StringVar(&cfg.dir, "dir", "", "scratch dir for review.md/review.log (default: a per-repo+branch tmp dir)")
	fs.StringVar(&cfg.tmplFile, "template", "", "path to a Go text/template overriding the default PR-comment template")
	fs.StringVar(&cfg.codexBin, "codex", "codex", "codex binary")
	fs.StringVar(&cfg.ghBin, "gh", "gh", "gh binary")
	_ = fs.Parse(args)

	if mode == "exec" && strings.TrimSpace(cfg.prompt) == "" {
		fail("exec mode requires --prompt")
	}
	if mode == "review" && cfg.prompt != "" {
		// Match the codex arg-parser constraint up front with a clear message.
		fail("review mode cannot take a --prompt (codex rejects [PROMPT] with --base/--commit); use 'codexreview exec --prompt ...' for a steered analysis")
	}
	return cfg
}

type result struct {
	Verdict    string
	Review     string
	ReviewPath string
	LogPath    string
	Duration   string
	Posted     string
}

func run(ctx context.Context, cfg config) (result, error) {
	if _, err := exec.LookPath(cfg.codexBin); err != nil {
		return result{}, fmt.Errorf("codex not on PATH (%q): %w", cfg.codexBin, err)
	}

	dir := cfg.dir
	if dir == "" {
		var derr error
		if dir, derr = scratchDir(); derr != nil {
			return result{}, derr
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return result{}, fmt.Errorf("mkdir scratch %s: %w", dir, err)
	}
	reviewPath := filepath.Join(dir, "review.md")
	logPath := filepath.Join(dir, "review.log")

	args := codexArgs(cfg)

	tctx, cancel := context.WithTimeout(ctx, cfg.timeout)
	defer cancel()

	cmd := exec.CommandContext(tctx, cfg.codexBin, args...)
	// Stdin == nil → /dev/null: this is the WHOLE POINT — `codex exec` hangs forever
	// reading an open stdin. Never connect a terminal/pipe here.
	cmd.Stdin = nil
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	// New process group so the timeout/interrupt kills codex AND its bwrap/sandbox
	// children, not just the parent.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	cmd.Cancel = func() error {
		if cmd.Process != nil {
			_ = syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
		}
		return cmd.Process.Kill()
	}

	start := time.Now()
	runErr := cmd.Run()
	dur := time.Since(start)

	_ = os.WriteFile(reviewPath, stdout.Bytes(), 0o644)
	_ = os.WriteFile(logPath, stderr.Bytes(), 0o644)

	review := strings.TrimSpace(stdout.String())
	logTail := tail(stderr.String(), 25)

	// Timeout is its own, clearly-labelled failure (not "codex found nothing").
	if errors.Is(tctx.Err(), context.DeadlineExceeded) {
		return result{}, fmt.Errorf("codex exceeded the --timeout of %s and was killed.\nlast stderr:\n%s\n(full log: %s)", cfg.timeout, logTail, logPath)
	}
	if errors.Is(ctx.Err(), context.Canceled) {
		return result{}, fmt.Errorf("interrupted; codex killed.\n(partial log: %s)", logPath)
	}

	// Empty review is NEVER a clean pass — it's quota/auth/error. Diagnose from stderr.
	if review == "" {
		diag := "no quota/auth signature found — inspect the full log"
		if m := quotaRE.FindString(stderr.String()); m != "" {
			diag = "looks like a quota/auth/stream failure (matched: " + m + ")"
		}
		return result{}, fmt.Errorf("codex produced an EMPTY review (exit err: %v) — this is a FAILED run, not an ACK.\n%s\nlast stderr:\n%s\n(full log: %s; also try `codex login status`)", runErr, diag, logTail, logPath)
	}
	// Non-empty review but codex exited non-zero: surface it, but the prose is usable.
	if runErr != nil {
		fmt.Fprintf(os.Stderr, "warning: codex exit error (%v) but a review was produced; proceeding.\n", runErr)
	}

	res := result{
		Verdict:    classifyVerdict(review),
		Review:     review,
		ReviewPath: reviewPath,
		LogPath:    logPath,
		Duration:   humanDur(dur),
	}

	if cfg.post {
		posted, err := postComment(ctx, cfg, res)
		if err != nil {
			return res, fmt.Errorf("review OK but posting failed: %w\n(review saved at %s — post by hand)", err, reviewPath)
		}
		res.Posted = posted
	}
	return res, nil
}

// codexArgs builds the codex argv with the REQUIRED flag ordering: global flags
// (-m, -c, -s|--bypass, -a) BEFORE the subcommand; subcommand options after.
func codexArgs(cfg config) []string {
	args := []string{"-m", cfg.model, "-c", "model_reasoning_effort=" + cfg.effort}
	if cfg.bypass {
		args = append(args, "--dangerously-bypass-approvals-and-sandbox")
	} else {
		args = append(args, "-s", "read-only")
	}
	args = append(args, "-a", "never")
	switch cfg.mode {
	case "review":
		args = append(args, "review")
		switch {
		case cfg.commit != "":
			args = append(args, "--commit", cfg.commit)
		case cfg.base != "":
			args = append(args, "--base", cfg.base)
		}
	case "exec":
		args = append(args, "exec", cfg.prompt)
	}
	return args
}

func classifyVerdict(review string) string {
	// Look at the last ~600 chars where the verdict lives.
	tailText := review
	if len(tailText) > 600 {
		tailText = tailText[len(tailText)-600:]
	}
	switch strings.ToUpper(verdictRE.FindString(tailText)) {
	case "NAK":
		return "NAK"
	case "ACK", "LGTM":
		return "ACK"
	}
	// Fall back to a full-text scan (some reviews put the verdict mid-prose).
	switch strings.ToUpper(verdictRE.FindString(review)) {
	case "NAK":
		return "NAK"
	case "ACK", "LGTM":
		return "ACK"
	}
	return "UNKNOWN (no ACK/NAK found — read the prose)"
}

func postComment(ctx context.Context, cfg config, res result) (string, error) {
	if _, err := exec.LookPath(cfg.ghBin); err != nil {
		return "", fmt.Errorf("gh not on PATH: %w", err)
	}
	body, err := renderComment(cfg, res)
	if err != nil {
		return "", err
	}
	args := []string{"pr", "comment"}
	if cfg.pr != "" {
		args = append(args, cfg.pr)
	}
	if cfg.repo != "" {
		args = append(args, "--repo", cfg.repo)
	}
	args = append(args, "--body-file", "-")
	cmd := exec.CommandContext(ctx, cfg.ghBin, args...)
	cmd.Stdin = strings.NewReader(body)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("gh %s: %w\n%s", strings.Join(args, " "), err, errb.String())
	}
	return strings.TrimSpace(out.String()), nil
}

type commentData struct {
	Kind, Duration, SHA, Review, Version, Model, Effort, SkillURL string
}

func renderComment(cfg config, res result) (string, error) {
	tmplText := commentTmpl
	if cfg.tmplFile != "" {
		b, err := os.ReadFile(cfg.tmplFile)
		if err != nil {
			return "", fmt.Errorf("read --template %s: %w", cfg.tmplFile, err)
		}
		tmplText = string(b)
	}
	t, err := template.New("comment").Parse(tmplText)
	if err != nil {
		return "", fmt.Errorf("parse comment template: %w", err)
	}
	kind := "finished review"
	if cfg.mode == "exec" {
		kind = "finished analysis"
	}
	data := commentData{
		Kind:     kind,
		Duration: res.Duration,
		SHA:      gitShort(),
		Review:   res.Review,
		Version:  codexVersion(cfg.codexBin),
		Model:    cfg.model,
		Effort:   cfg.effort,
		SkillURL: cfg.skillURL,
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute comment template: %w", err)
	}
	return buf.String(), nil
}

// --- small helpers (git/codex/util) ---

func scratchDir() (string, error) {
	top, err := gitOutput("rev-parse", "--show-toplevel")
	if err != nil {
		return "", fmt.Errorf("not in a git repo: %w", err)
	}
	br, _ := gitOutput("rev-parse", "--abbrev-ref", "HEAD")
	tmp := os.Getenv("TMPDIR")
	if tmp == "" {
		tmp = "/tmp"
	}
	safe := regexp.MustCompile(`[^A-Za-z0-9._-]`).ReplaceAllString(br, "_")
	// cksum-style stable key off the repo path so concurrent reviews never clash.
	key := fmt.Sprintf("%08x", crc(top))
	return filepath.Join(tmp, "codex-review", key+"-"+safe), nil
}

func crc(s string) uint32 {
	var h uint32 = 2166136261
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return h
}

func gitOutput(args ...string) (string, error) {
	out, err := exec.Command("git", args...).Output()
	return strings.TrimSpace(string(out)), err
}

func gitShort() string {
	s, _ := gitOutput("rev-parse", "--short", "HEAD")
	if s == "" {
		return "unknown"
	}
	return s
}

var semverRE = regexp.MustCompile(`[0-9]+(\.[0-9]+)+`)

func codexVersion(bin string) string {
	out, _ := exec.Command(bin, "--version").Output()
	if v := semverRE.FindString(string(out)); v != "" {
		return v
	}
	return "unknown"
}

func env(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func tail(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}

func countLines(s string) int {
	if s == "" {
		return 0
	}
	return strings.Count(s, "\n") + 1
}

func humanDur(d time.Duration) string {
	d = d.Round(time.Second)
	return fmt.Sprintf("%dm%02ds", int(d.Minutes()), int(d.Seconds())%60)
}

func fail(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "codexreview: "+format+"\n", a...)
	os.Exit(1)
}
