// Command codexreview manages an OpenAI Codex (`codex` CLI) code review end to end:
// it invokes codex in a way that CANNOT hang, captures stdout/stderr, detects the
// real failure modes (quota/auth/empty), parses the ACK/NAK verdict, renders a
// PR comment from a Go template, and posts it with `gh`.
//
// Why a tool instead of a shell one-liner: `codex exec` blocks FOREVER if its stdin
// is left open (it waits to "read additional input from stdin"); a piped
// `codex exec ... | tail` hangs exactly this way. An exec.Cmd with Stdin == nil
// connects the child to /dev/null, so the hang is structurally impossible — and a
// hard context timeout + process-group kill is the backstop.
//
// Subcommands:
//
//	codexreview review  --base <branch|sha>   [flags]   # diff review of a branch/range
//	codexreview exec    --prompt "<steer>"    [flags]   # steered analysis (review can't take a prompt)
//
// Common flags: --model, --effort, --timeout, --post, --pr, --repo, --bypass-sandbox, --skill-url, --dir.
//
// Progress: a multi-minute run is NOT silent. The tool prints a heartbeat to stderr
// every --heartbeat seconds (default 15s) with elapsed time, tokens used, and
// turns/tool-calls so far, plus the latest activity line — so you NEVER need to pipe
// codex through `tail`/`grep` to "see if it's alive" (which also truncates the
// verdict). `-v/--verbose` streams codex's full live trace to stderr too. Metrics come
// from the real event stream: exec mode runs codex with `--json` (turn/usage events);
// review mode parses codex's human trace (tool-call markers + `tokens used`).
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"text/template"
	"time"
)

const defaultSkillURL = "https://github.com/birdayz/skills/tree/master/codex-review"

// commentMarker is an invisible HTML comment appended to every posted comment so
// re-reviews can find-and-update the tool's PRIOR comment instead of spamming the PR
// (--supersede). It is template-independent (a custom --template still gets it).
const commentMarker = "<!-- codexreview:marker -->"

// commentTmpl is the PR-comment template — the same shape the skill documents, but
// rendered from data instead of an unquoted printf. Kept overridable via --template.
// The footer carries run stats (tokens · turns · tool-calls) so a reader can gauge how
// much work the review did at a glance.
const commentTmpl = "**Codex {{.Kind}}{{with .Duration}} in {{.}}{{end}}** · `{{.SHA}}`\n\n" +
	"---\n\n{{.Review}}\n\n---\n\n" +
	"`{{.Stats}}` · Generated by Codex {{.Version}} on {{.Model}} ({{.Effort}}) and [codex-review]({{.SkillURL}})"

// quotaRE matches the stderr signatures of a non-error EMPTY run: an exit-0 codex
// that produced no verdict because it was rate-limited, unauthenticated, or errored
// mid-stream. An empty review is NEVER a clean pass.
var quotaRE = regexp.MustCompile(`(?i)rate.?limit|quota|usage limit|429|too many|reached|not logged in|unauthor|stream error|error:|ContextWindowExceeded|UsageLimitExceeded`)

// verdictLineRE matches a VERDICT LINE — a line whose first word (after optional
// markdown bullets / emphasis / quote markers) is ACK / NAK / LGTM. Anchored to the
// line start so a verdict word buried mid-prose ("this isn't a clean ACK", "would
// NAK if…") does NOT count. Code spans are stripped before matching. The trailing
// `(?:\b|_)` also closes on a `_` so underscore-emphasis (`_NAK_`) matches, while a
// longer word (`NAKED`, `ACKNOWLEDGE`) still does not.
var verdictLineRE = regexp.MustCompile(`(?im)^[\s>*_#-]*(ACK|NAK|LGTM)(?:\b|_)`)

// fencedRE / inlineCodeRE strip fenced blocks and inline-code spans so a verdict
// word quoted inside code can never be read as the reviewer's verdict.
var (
	fencedRE     = regexp.MustCompile("(?s)```.*?```")
	inlineCodeRE = regexp.MustCompile("`[^`]*`")
)

// worktreePathRE matches an absolute path up to and including a `.claude/worktrees/<name>/`
// segment. It's the best-effort fallback in stripRepoPaths: a path codex emitted from inside
// a Claude Code worktree collapses to its repo-relative tail even when the exact work-tree
// root wasn't computed (symlink-resolved path, a stale toplevel). The `[^\s:]` classes keep
// a match inside one path token and short of the trailing `:line` suffix.
var worktreePathRE = regexp.MustCompile(`/[^\s:]*\.claude/worktrees/[^/\s:]+/`)

type config struct {
	mode      string // "review" | "exec"
	base      string
	commit    string
	prompt    string
	model     string
	effort    string
	timeout   time.Duration
	post      bool
	supersede bool
	pr        string
	repo      string
	bypass    bool
	keepPaths bool
	skillURL  string
	dir       string
	tmplFile  string
	codexBin  string
	ghBin     string
	verbose   bool
	heartbeat time.Duration
}

func main() {
	if len(os.Args) < 2 {
		usage(os.Stderr)
		os.Exit(2)
	}
	switch os.Args[1] {
	case "-h", "--help", "help":
		usage(os.Stdout)
		return
	case "review", "exec":
		// valid subcommand — fall through to parse its flags
	default:
		fmt.Fprintf(os.Stderr, "codexreview: unknown command %q\n\n", os.Args[1])
		usage(os.Stderr)
		os.Exit(2)
	}
	cfg := parseFlags(os.Args[1], os.Args[2:])

	// One Ctrl-C cleanly cancels the run (kills the whole codex process group).
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	res, err := run(ctx, cfg)
	if err != nil {
		fail("%v", err)
	}

	// Always surface the verdict + run stats + scratch paths for the caller.
	fmt.Printf("VERDICT: %s\n", res.Verdict)
	fmt.Printf("stats: %s · %s\n", res.Duration, res.metricsLine())
	fmt.Printf("review: %s  (%d lines)  ·  log: %s\n", res.ReviewPath, countLines(res.Review), res.LogPath)
	if res.Posted != "" {
		fmt.Printf("posted: %s\n", res.Posted)
	}
	// Echo the review prose so the caller (an agent) reads it inline.
	fmt.Printf("\n----- review -----\n%s\n", strings.TrimSpace(res.Review))
}

// parseFlags parses the flags for a validated mode ("review"|"exec"); main guarantees
// the mode before calling, so there's no mode check here.
func parseFlags(mode string, args []string) config {
	fs := flag.NewFlagSet("codexreview "+mode, flag.ExitOnError)
	cfg := config{mode: mode}
	// Mode-specific flags are registered ONLY for their mode, so `review -h` and
	// `exec -h` each show just the flags that apply (no cross-mode noise).
	switch mode {
	case "review":
		fs.StringVar(&cfg.base, "base", "", "base branch/sha to diff against (default = PR base or repo default)")
		fs.StringVar(&cfg.commit, "commit", "", "review a single commit instead of a range")
	case "exec":
		fs.StringVar(&cfg.prompt, "prompt", "", "the steering prompt (required)")
	}
	fs.StringVar(&cfg.model, "model", env("CODEX_REVIEW_MODEL", "gpt-5.6-sol"), "codex model (-m)")
	fs.StringVar(&cfg.effort, "effort", env("CODEX_REVIEW_REASONING_EFFORT", "ultra"), "reasoning effort (-c model_reasoning_effort=)")
	fs.DurationVar(&cfg.timeout, "timeout", 25*time.Minute, "hard wall-clock cap; the run is killed (process group) if exceeded")
	fs.BoolVar(&cfg.post, "post", false, "post the review as a PR comment via gh")
	fs.BoolVar(&cfg.supersede, "supersede", false, "with --post: post a NEW comment and COLLAPSE this tool's prior comments on the PR as 'outdated' (re-reviews keep one active comment + a folded history, no edit-in-place, no spam)")
	fs.BoolVar(&cfg.supersede, "update-last", false, "deprecated alias for --supersede")
	fs.StringVar(&cfg.pr, "pr", "", "PR number to post to (default: the current branch's PR)")
	fs.StringVar(&cfg.repo, "repo", "", "owner/name for gh (default: inferred from cwd)")
	fs.BoolVar(&cfg.bypass, "bypass-sandbox", false, "use --dangerously-bypass-approvals-and-sandbox instead of -s read-only (REQUIRED inside a nested sandbox/agent where bwrap can't nest; review writes nothing, so no edit risk)")
	fs.BoolVar(&cfg.keepPaths, "keep-paths", false, "keep codex's absolute file paths in the review (default: rewrite them to repo-relative so a posted comment doesn't leak the local repo/worktree path)")
	fs.StringVar(&cfg.skillURL, "skill-url", defaultSkillURL, "skill URL for the comment footer")
	fs.StringVar(&cfg.dir, "dir", "", "scratch dir for review.md/review.log (default: a per-repo+branch tmp dir)")
	fs.StringVar(&cfg.tmplFile, "template", "", "path to a Go text/template overriding the default PR-comment template")
	fs.StringVar(&cfg.codexBin, "codex", "codex", "codex binary")
	fs.StringVar(&cfg.ghBin, "gh", "gh", "gh binary")
	fs.BoolVar(&cfg.verbose, "v", false, "stream codex's full live trace to stderr (async runs only — floods a sync call's output)")
	fs.BoolVar(&cfg.verbose, "verbose", false, "alias for -v")
	fs.DurationVar(&cfg.heartbeat, "heartbeat", 15*time.Second, "progress heartbeat interval (elapsed · tokens · turns/tool-calls · activity); 0 disables")
	_ = fs.Parse(args)

	if mode == "exec" && strings.TrimSpace(cfg.prompt) == "" {
		fail("exec mode requires --prompt")
	}
	return cfg
}

// usage prints the top-level help: both subcommands, the key defaults, and where to
// find per-subcommand flags. Goes to stdout for `-h`, stderr for a bare/invalid call.
func usage(w *os.File) {
	fmt.Fprint(w, `codexreview — drive an OpenAI Codex (`+"`codex`"+`) code review end to end.

usage:
  codexreview review [--base <branch|sha> | --commit <sha>] [flags]   diff review of a branch/range
  codexreview exec   --prompt "<steer>"                    [flags]    steered analysis (review can't take a prompt)

common flags (full list: `+"`codexreview review -h`"+` / `+"`codexreview exec -h`"+`):
  --post                post the result as a PR comment via gh (--supersede collapses prior ones)
  --model   gpt-5.6-sol codex model           (env CODEX_REVIEW_MODEL)
  --effort  ultra       reasoning effort      (env CODEX_REVIEW_REASONING_EFFORT)
  --timeout 25m         hard cap; a stuck run is process-group-killed (no external `+"`timeout`"+` needed)
  --heartbeat 15s       stderr progress line (elapsed · tokens · turns/tool-calls · activity); 0 disables
  -v/--verbose          stream codex's full live trace to stderr (async runs only)
  --bypass-sandbox      REQUIRED inside a nested sandbox/agent (codex's bwrap can't nest)

Run it directly with `+"`go run`"+` — no build needed; it runs in your current repo:
  GOWORK=off go run /path/to/codexreview/main.go review --base main --post

It cannot hang (stdin is closed + hard timeout), never reports ACK on an empty/quota/
timeout failure, and saves review.md + a live review.log in the scratch dir.
`)
}

type result struct {
	Verdict    string
	Review     string
	ReviewPath string
	LogPath    string
	Duration   string
	Posted     string
	Mode       string // "review" | "exec" — controls which run stats are meaningful
	Turns      int    // exec only (review has no turn concept)
	ToolCalls  int    // commands codex ran while reviewing
	Tokens     int    // total tokens (input+output) reported by codex
}

// metricsLine renders the run's resource stats compactly (tokens + tool-calls always,
// turns only for exec) — WITHOUT duration, which callers show separately (the comment
// header and the stdout summary already carry it, so repeating it reads as clutter).
func (r result) metricsLine() string {
	var parts []string
	if r.Tokens > 0 {
		parts = append(parts, humanInt(r.Tokens)+" tokens")
	}
	if r.Mode == "exec" {
		parts = append(parts, plural(r.Turns, "turn"))
	}
	parts = append(parts, plural(r.ToolCalls, "tool-call"))
	return strings.Join(parts, " · ")
}

func run(ctx context.Context, cfg config) (result, error) {
	if _, err := exec.LookPath(cfg.codexBin); err != nil {
		return result{}, fmt.Errorf("codex not on PATH (%q): %w", cfg.codexBin, err)
	}

	dir := cfg.dir
	if dir == "" {
		var derr error
		if dir, derr = scratchDir(); derr != nil {
			return result{}, derr
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return result{}, fmt.Errorf("mkdir scratch %s: %w", dir, err)
	}
	reviewPath := filepath.Join(dir, "review.md")
	logPath := filepath.Join(dir, "review.log")
	lastMsgPath := filepath.Join(dir, "last-message.txt")

	args := codexArgs(cfg, lastMsgPath)

	tctx, cancel := context.WithTimeout(ctx, cfg.timeout)
	defer cancel()

	cmd := exec.CommandContext(tctx, cfg.codexBin, args...)
	// Stdin == nil → /dev/null: this is the WHOLE POINT — `codex exec` hangs forever
	// reading an open stdin. Never connect a terminal/pipe here.
	cmd.Stdin = nil
	// The progress TRACE and the review PROSE arrive on different streams per mode:
	//   review: prose on stdout, codex's human trace on stderr.
	//   exec  : `--json` event stream on stdout (the trace we parse), prose written to
	//           lastMsgPath via `-o`, and stderr is just diagnostics.
	// `tracker` wraps whichever stream carries the trace: it bounds the capture, streams
	// it live to the log file (`tail -f`), parses metrics (tokens / turns / tool-calls)
	// for the heartbeat, and — with -v — echoes the trace to stderr as it arrives.
	logFile, _ := os.Create(logPath)
	if logFile != nil {
		defer logFile.Close()
	}
	tracker := &liveTracker{cap: &capBuffer{max: 8 << 20}, file: logFile, echo: cfg.verbose, jsonMode: cfg.mode == "exec"}
	proseCap := &capBuffer{max: 8 << 20} // review: stdout prose; exec: unused (prose comes from lastMsgPath)
	diagCap := &capBuffer{max: 8 << 20}  // exec: stderr diagnostics; review: unused
	if cfg.mode == "exec" {
		cmd.Stdout = tracker
		cmd.Stderr = diagCap
	} else {
		cmd.Stdout = proseCap
		cmd.Stderr = tracker
	}
	// New process group so the timeout/interrupt kills codex AND its bwrap/sandbox
	// children, not just the parent.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	cmd.Cancel = func() error {
		if cmd.Process == nil {
			return nil
		}
		// Kill the whole group (codex + its bwrap sandbox children); the negative pid
		// targets the group leader's group. Fall back to killing the process directly.
		_ = syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
		return cmd.Process.Kill()
	}
	// Backstop: if Cancel's kill races a child that hasn't reparented, don't block
	// forever in Wait — force-return shortly after.
	cmd.WaitDelay = 10 * time.Second

	trace := "live trace: tail -f " + logPath
	if logFile == nil {
		trace = "(could not open log file " + logPath + ")"
	}
	fmt.Fprintf(os.Stderr, "codexreview: %s · %s (%s) · timeout %s · heartbeat %s%s · %s\n",
		cfg.mode, cfg.model, cfg.effort, cfg.timeout, hbLabel(cfg.heartbeat), verboseLabel(cfg.verbose), trace)

	start := time.Now()
	// Heartbeat: print a progress line every cfg.heartbeat so the caller sees codex is
	// alive and advancing (tokens climbing, turns/tool-calls accruing) instead of minutes
	// of silence. 0 disables it (e.g. when -v already streams everything).
	hbDone := make(chan struct{})
	go heartbeat(cfg, start, tracker, hbDone)

	runErr := cmd.Run()
	close(hbDone)
	dur := time.Since(start)

	// Recover the review prose by mode: exec writes the final agent message to
	// lastMsgPath (stdout was the JSON event stream); review's prose IS stdout.
	var review string
	if cfg.mode == "exec" {
		b, _ := os.ReadFile(lastMsgPath)
		review = strings.TrimSpace(string(b))
	} else {
		review = strings.TrimSpace(proseCap.String())
	}
	// Rewrite codex's absolute paths to repo-relative BEFORE anything consumes the prose
	// (review.md, verdict, PR comment, stdout echo) so none of them leak the local repo or
	// worktree path. The full trace in review.log keeps absolute paths — it's local debug.
	if review != "" && !cfg.keepPaths {
		review = stripRepoPaths(review, repoRoots())
	}
	_ = os.WriteFile(reviewPath, []byte(review), 0o644)
	// logPath was streamed live via logFile — don't truncate it here.

	// Diagnostics come from the trace plus (exec) the stderr diag stream.
	diagSrc := tracker.cap.String()
	if cfg.mode == "exec" {
		diagSrc += "\n" + diagCap.String()
	}
	logTail := tail(diagSrc, 25)

	// Timeout is its own, clearly-labelled failure (not "codex found nothing").
	if errors.Is(tctx.Err(), context.DeadlineExceeded) {
		return result{}, fmt.Errorf("codex exceeded the --timeout of %s and was killed.\nlast trace:\n%s\n(full log: %s)", cfg.timeout, logTail, logPath)
	}
	if errors.Is(ctx.Err(), context.Canceled) {
		return result{}, fmt.Errorf("interrupted; codex killed.\n(partial log: %s)", logPath)
	}

	// Empty review is NEVER a clean pass — it's quota/auth/error. Diagnose from the trace.
	if review == "" {
		diag := "no quota/auth signature found — inspect the full log"
		if m := quotaRE.FindString(diagSrc); m != "" {
			diag = "looks like a quota/auth/stream failure (matched: " + m + ")"
		}
		return result{}, fmt.Errorf("codex produced an EMPTY review (exit err: %v) — this is a FAILED run, not an ACK.\n%s\nlast trace:\n%s\n(full log: %s; also try `codex login status`)", runErr, diag, logTail, logPath)
	}
	// Non-empty review but codex exited non-zero: surface it, but the prose is usable.
	if runErr != nil {
		fmt.Fprintf(os.Stderr, "warning: codex exit error (%v) but a review was produced; proceeding.\n", runErr)
	}

	turns, tools, tokens, _, _ := tracker.progress()
	res := result{
		Verdict:    classifyVerdict(review),
		Review:     review,
		ReviewPath: reviewPath,
		LogPath:    logPath,
		Duration:   humanDur(dur),
		Mode:       cfg.mode,
		Turns:      turns,
		ToolCalls:  tools,
		Tokens:     tokens,
	}

	if cfg.post {
		posted, err := postComment(ctx, cfg, res)
		if err != nil {
			return res, fmt.Errorf("review OK but posting failed: %w\n(review saved at %s — post by hand)", err, reviewPath)
		}
		res.Posted = posted
	}
	return res, nil
}

// codexArgs builds the codex argv with the REQUIRED flag ordering: global flags
// (-m, -c, -s|--bypass[, -a]) BEFORE the subcommand; subcommand options after.
//
// --dangerously-bypass-approvals-and-sandbox ALREADY disables both approvals and the
// sandbox; codex REJECTS combining it with -a/--ask-for-approval ("cannot be used with
// '--ask-for-approval'"). So -a never is added ONLY on the sandboxed (-s read-only) path.
//
// exec runs with `--json` (so we parse the turn/usage event stream for live metrics)
// and `-o lastMsgPath` (so the final agent message lands in a file as clean prose —
// stdout is the JSON stream, not the answer). `review` has no --json; its prose is
// stdout and its trace is the human stderr stream.
func codexArgs(cfg config, lastMsgPath string) []string {
	args := []string{"-m", cfg.model, "-c", "model_reasoning_effort=" + cfg.effort}
	if cfg.bypass {
		args = append(args, "--dangerously-bypass-approvals-and-sandbox")
	} else {
		args = append(args, "-s", "read-only", "-a", "never")
	}
	switch cfg.mode {
	case "review":
		args = append(args, "review")
		switch {
		case cfg.commit != "":
			args = append(args, "--commit", cfg.commit)
		case cfg.base != "":
			args = append(args, "--base", cfg.base)
		}
	case "exec":
		args = append(args, "exec", "--json", "-o", lastMsgPath, cfg.prompt)
	}
	return args
}

// classifyVerdict extracts the ACK/NAK/LGTM verdict. It scans VERDICT LINES (not
// mid-prose mentions, not code spans) and applies NAK PRECEDENCE: if a blocking NAK
// appears anywhere, the verdict is NAK even when an ACK line is also present (e.g.
// "ACK for the docs … NAK on the code") — a blocking finding must never be masked by
// a co-occurring ACK. Returns UNKNOWN (never a guessed ACK) when no verdict line is
// found — the safe default is "make the human read the prose", not a false pass.
func classifyVerdict(review string) string {
	clean := inlineCodeRE.ReplaceAllString(fencedRE.ReplaceAllString(review, ""), "")
	var sawACK, sawNAK bool
	for _, m := range verdictLineRE.FindAllStringSubmatch(clean, -1) {
		switch strings.ToUpper(m[1]) {
		case "NAK":
			sawNAK = true
		case "ACK", "LGTM":
			sawACK = true
		}
	}
	switch {
	case sawNAK:
		return "NAK"
	case sawACK:
		return "ACK"
	default:
		return "UNKNOWN (no ACK/NAK verdict line — read the prose)"
	}
}

// stripRepoPaths rewrites the absolute file paths in codex's review prose into
// repo-relative ones. Codex reports each finding with the absolute path of the directory
// it ran in — e.g. "/home/me/proj/.claude/worktrees/r-14/apps/x.tsx:5". Posting that into
// a PR comment leaks the reviewer's local filesystem layout (home dir, worktree name) and
// makes the path un-clickable for everyone else, so we collapse the repo-root prefix and
// the finding reads "apps/x.tsx:5".
//
// roots are the absolute directory prefixes to strip, longest first (caller supplies them;
// see repoRoots). After the exact prefixes, a best-effort pass collapses any leftover
// `<…>/.claude/worktrees/<name>/` prefix, catching paths whose exact root wasn't computed
// (symlink-resolved, stale toplevel).
func stripRepoPaths(review string, roots []string) string {
	for _, r := range roots {
		if r != "" {
			review = strings.ReplaceAll(review, r+"/", "")
		}
	}
	return worktreePathRE.ReplaceAllString(review, "")
}

// repoRoots returns the absolute directory prefixes stripRepoPaths should remove, longest
// first so the most specific match wins. It's the git work-tree root of codex's cwd (which
// IS the worktree path when the review ran inside one) plus its symlink-resolved form and
// the cwd, deduped — the set of strings codex could have prefixed a path with.
func repoRoots() []string {
	seen := map[string]bool{}
	var roots []string
	add := func(p string) {
		if p == "" || seen[p] {
			return
		}
		seen[p] = true
		roots = append(roots, p)
	}
	if top, err := gitOutput("rev-parse", "--show-toplevel"); err == nil {
		add(top)
		if real, err := filepath.EvalSymlinks(top); err == nil {
			add(real)
		}
	}
	if cwd, err := os.Getwd(); err == nil {
		add(cwd)
		if real, err := filepath.EvalSymlinks(cwd); err == nil {
			add(real)
		}
	}
	sort.Slice(roots, func(i, j int) bool { return len(roots[i]) > len(roots[j]) })
	return roots
}

func postComment(ctx context.Context, cfg config, res result) (string, error) {
	if _, err := exec.LookPath(cfg.ghBin); err != nil {
		return "", fmt.Errorf("gh not on PATH: %w", err)
	}
	body, err := renderComment(cfg, res)
	if err != nil {
		return "", err
	}

	// --supersede: collapse this tool's PRIOR comments as "outdated" (GitHub's
	// minimizeComment) BEFORE posting the fresh one. A re-review loop then shows ONE
	// active comment with the earlier ones folded away — preserving history (no
	// edit-in-place) without spamming N expanded comments. Best-effort: a collapse
	// failure (auth/scope) never blocks the new comment.
	collapsed := 0
	if cfg.supersede {
		if slug, err := ghJSON(ctx, cfg, "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"); err == nil && slug != "" {
			pr := cfg.pr
			if pr == "" {
				pr, _ = ghJSON(ctx, cfg, "pr", "view", "--json", "number", "-q", ".number")
			}
			if pr != "" {
				collapsed, _ = minimizePriorComments(ctx, cfg, slug, pr)
			}
		}
	}

	args := []string{"pr", "comment"}
	if cfg.pr != "" {
		args = append(args, cfg.pr)
	}
	if cfg.repo != "" {
		args = append(args, "--repo", cfg.repo)
	}
	args = append(args, "--body-file", "-")
	cmd := exec.CommandContext(ctx, cfg.ghBin, args...)
	cmd.Stdin = strings.NewReader(body)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("gh %s: %w\n%s", strings.Join(args, " "), err, errb.String())
	}
	url := strings.TrimSpace(out.String())
	if collapsed > 0 {
		url += fmt.Sprintf(" (collapsed %d prior)", collapsed)
	}
	return url, nil
}

// minimizePriorComments collapses every issue comment on the PR that carries this
// tool's marker as "outdated" (GitHub's hide-as-outdated), returning how many it
// collapsed. minimizeComment is idempotent, so re-running over already-collapsed
// comments is harmless.
func minimizePriorComments(ctx context.Context, cfg config, slug, pr string) (int, error) {
	// minimizeComment is a GraphQL mutation keyed by the comment's NODE id, so select
	// node_id (not the REST numeric id) of every marker-bearing comment.
	jq := fmt.Sprintf(`.[] | select(.body | contains(%q)) | .node_id`, commentMarker)
	out, err := exec.CommandContext(ctx, cfg.ghBin, "api", "--paginate",
		fmt.Sprintf("repos/%s/issues/%s/comments", slug, pr), "--jq", jq).Output()
	if err != nil {
		return 0, err
	}
	n := 0
	for _, nodeID := range strings.Fields(string(out)) {
		if err := minimizeComment(ctx, cfg, nodeID); err == nil {
			n++
		}
	}
	return n, nil
}

// minimizeComment hides a single comment as OUTDATED via the GraphQL minimizeComment
// mutation (the REST API has no collapse endpoint). Idempotent on an already-minimized
// comment.
func minimizeComment(ctx context.Context, cfg config, nodeID string) error {
	const q = `mutation($id:ID!){minimizeComment(input:{subjectId:$id,classifier:OUTDATED}){minimizedComment{isMinimized}}}`
	cmd := exec.CommandContext(ctx, cfg.ghBin, "api", "graphql", "-f", "query="+q, "-f", "id="+nodeID)
	return cmd.Run()
}

// ghJSON runs a gh command and returns trimmed stdout (used for tiny -q scalars).
func ghJSON(ctx context.Context, cfg config, args ...string) (string, error) {
	if cfg.repo != "" && (len(args) > 0 && args[0] != "api") {
		args = append(args, "--repo", cfg.repo)
	}
	out, err := exec.CommandContext(ctx, cfg.ghBin, args...).Output()
	return strings.TrimSpace(string(out)), err
}

type commentData struct {
	Kind, Duration, SHA, Review, Version, Model, Effort, SkillURL string
	Stats                                                         string // pre-rendered "2m21s · 18.4k tokens · 47 tool-calls"
	Turns, ToolCalls, Tokens                                      int    // raw, for custom --template authors
}

func renderComment(cfg config, res result) (string, error) {
	tmplText := commentTmpl
	if cfg.tmplFile != "" {
		b, err := os.ReadFile(cfg.tmplFile)
		if err != nil {
			return "", fmt.Errorf("read --template %s: %w", cfg.tmplFile, err)
		}
		tmplText = string(b)
	}
	t, err := template.New("comment").Parse(tmplText)
	if err != nil {
		return "", fmt.Errorf("parse comment template: %w", err)
	}
	kind := "finished review"
	if cfg.mode == "exec" {
		kind = "finished analysis"
	}
	data := commentData{
		Kind:      kind,
		Duration:  res.Duration,
		SHA:       gitShort(),
		Review:    res.Review,
		Version:   codexVersion(cfg.codexBin),
		Model:     cfg.model,
		Effort:    cfg.effort,
		SkillURL:  cfg.skillURL,
		Stats:     res.metricsLine(),
		Turns:     res.Turns,
		ToolCalls: res.ToolCalls,
		Tokens:    res.Tokens,
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute comment template: %w", err)
	}
	// Append the invisible marker (template-independent) so --supersede can find
	// this comment on a later re-review.
	return buf.String() + "\n\n" + commentMarker, nil
}

// capBuffer is an io.Writer that retains at most max bytes (the first max) but
// reports every write as fully consumed, so a child writing past the cap is never
// blocked on backpressure — it just stops being recorded past the ceiling.
type capBuffer struct {
	buf bytes.Buffer
	max int
}

func (c *capBuffer) Write(p []byte) (int, error) {
	if room := c.max - c.buf.Len(); room > 0 {
		if room > len(p) {
			room = len(p)
		}
		c.buf.Write(p[:room])
	}
	return len(p), nil
}

func (c *capBuffer) Bytes() []byte  { return c.buf.Bytes() }
func (c *capBuffer) String() string { return c.buf.String() }

// liveTracker is the central progress reader. It (1) bounds the captured trace for the
// final quota/tail diagnosis, (2) streams every write to the log file as it arrives
// (`tail -f review.log`), (3) parses the trace line-by-line into live metrics — tokens,
// turns, tool-calls, and the latest activity — for the heartbeat, and (4) with echo
// (-v) mirrors a humanized trace line to stderr as it happens.
//
// jsonMode switches the parser: exec emits `--json` events (turn.*/item.* with usage),
// review emits codex's human trace (bare `exec` markers + a `tokens used` block).
type liveTracker struct {
	cap      *capBuffer
	file     *os.File
	echo     bool // -v: mirror a humanized trace line to stderr live
	jsonMode bool // exec: parse JSONL events; review: parse the human text trace

	mu        sync.Mutex
	last      string // latest activity (a command, a message snippet, a reasoning line)
	lines     int    // non-empty lines seen — pure liveness signal
	turns     int    // exec: completed turns
	toolCalls int    // exec: command_execution items; review: `exec` markers
	tokens    int    // latest token total (input+output)
	partial   []byte
	expectTok bool // review text: the line after a bare `tokens used` is the count
}

func (t *liveTracker) Write(p []byte) (int, error) {
	t.cap.Write(p)
	if t.file != nil {
		_, _ = t.file.Write(p) // live stream; best-effort
	}
	t.mu.Lock()
	t.partial = append(t.partial, p...)
	for {
		i := bytes.IndexByte(t.partial, '\n')
		if i < 0 {
			break
		}
		line := strings.TrimSpace(string(t.partial[:i]))
		t.partial = t.partial[i+1:]
		if line == "" {
			continue
		}
		t.lines++
		if t.jsonMode {
			t.parseJSON(line)
		} else {
			t.parseText(line)
		}
	}
	t.mu.Unlock()
	return len(p), nil
}

// codexEvent is the subset of the `codex exec --json` JSONL schema we read.
type codexEvent struct {
	Type string `json:"type"`
	Item *struct {
		Type    string `json:"type"`
		Text    string `json:"text"`
		Command string `json:"command"`
	} `json:"item"`
	Usage *struct {
		InputTokens  int `json:"input_tokens"`
		OutputTokens int `json:"output_tokens"`
	} `json:"usage"`
}

// parseJSON updates metrics from one exec `--json` event line. Caller holds t.mu.
func (t *liveTracker) parseJSON(line string) {
	var ev codexEvent
	if json.Unmarshal([]byte(line), &ev) != nil {
		return
	}
	switch ev.Type {
	case "turn.completed":
		t.turns++
		if ev.Usage != nil {
			t.tokens = ev.Usage.InputTokens + ev.Usage.OutputTokens
		}
		t.echoLine(fmt.Sprintf("turn %d done · %s tokens", t.turns, humanInt(t.tokens)))
	case "item.started", "item.completed":
		if ev.Item == nil {
			return
		}
		switch ev.Item.Type {
		case "command_execution":
			// Count + announce a tool call once, when it STARTS (item.completed would
			// double it).
			if ev.Type != "item.started" {
				return
			}
			t.toolCalls++
			if c := firstLine(ev.Item.Command); c != "" {
				t.last = "exec: " + c
				t.echoLine(t.last)
			}
		case "agent_message":
			// The message text arrives on completion.
			if ev.Type == "item.completed" {
				if s := firstLine(ev.Item.Text); s != "" {
					t.last = "msg: " + s
					t.echoLine(t.last)
				}
			}
		case "reasoning":
			if s := firstLine(ev.Item.Text); s != "" {
				t.last = s
				t.echoLine("thinking: " + s)
			}
		}
	}
}

// parseText updates metrics from one review human-trace line. codex prints a bare
// `exec` line before each tool command, and a `tokens used` line whose successor is the
// count (e.g. "18,358"). Caller holds t.mu.
func (t *liveTracker) parseText(line string) {
	if t.expectTok {
		t.expectTok = false
		if n := parseInt(line); n > 0 {
			t.tokens = n
			t.echoLine(line)
			return
		}
		// Not the count we expected (codex didn't print one) — don't swallow this line;
		// fall through so a following `exec` marker / activity line is still counted.
	}
	switch {
	case line == "tokens used":
		t.expectTok = true
	case line == "exec":
		t.toolCalls++
	default:
		t.last = line
	}
	t.echoLine(line)
}

// echoLine mirrors a line to stderr when -v is set. Caller holds t.mu (cheap write).
func (t *liveTracker) echoLine(s string) {
	if t.echo && s != "" {
		fmt.Fprintf(os.Stderr, "  | %s\n", clip(s, 200))
	}
}

// progress is an atomic snapshot for the heartbeat.
func (t *liveTracker) progress() (turns, toolCalls, tokens, lines int, last string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.turns, t.toolCalls, t.tokens, t.lines, t.last
}

// --- small helpers (git/codex/util) ---

func scratchDir() (string, error) {
	top, err := gitOutput("rev-parse", "--show-toplevel")
	if err != nil {
		return "", fmt.Errorf("not in a git repo: %w", err)
	}
	br, _ := gitOutput("rev-parse", "--abbrev-ref", "HEAD")
	tmp := os.Getenv("TMPDIR")
	if tmp == "" {
		tmp = "/tmp"
	}
	safe := regexp.MustCompile(`[^A-Za-z0-9._-]`).ReplaceAllString(br, "_")
	// Stable per-repo key (FNV-1a of the repo path) so concurrent reviews of
	// different repos/branches never clash on the scratch dir.
	key := fmt.Sprintf("%08x", fnv1a(top))
	return filepath.Join(tmp, "codex-review", key+"-"+safe), nil
}

func fnv1a(s string) uint32 {
	var h uint32 = 2166136261
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return h
}

func gitOutput(args ...string) (string, error) {
	out, err := exec.Command("git", args...).Output()
	return strings.TrimSpace(string(out)), err
}

func gitShort() string {
	s, _ := gitOutput("rev-parse", "--short", "HEAD")
	if s == "" {
		return "unknown"
	}
	return s
}

var semverRE = regexp.MustCompile(`[0-9]+(\.[0-9]+)+`)

func codexVersion(bin string) string {
	out, _ := exec.Command(bin, "--version").Output()
	if v := semverRE.FindString(string(out)); v != "" {
		return v
	}
	return "unknown"
}

func env(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func tail(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}

func countLines(s string) int {
	if s == "" {
		return 0
	}
	return strings.Count(s, "\n") + 1
}

func humanDur(d time.Duration) string {
	d = d.Round(time.Second)
	return fmt.Sprintf("%dm%02ds", int(d.Minutes()), int(d.Seconds())%60)
}

// heartbeat prints a progress line every cfg.heartbeat until done: elapsed wall-clock,
// tokens used, turns (exec) or tool-calls (review) so far, and the latest activity —
// so the caller knows codex is alive and advancing without piping it through `tail`.
// Goes to stderr so it interleaves with the trace, not the final verdict on stdout.
// A non-positive interval disables it.
func heartbeat(cfg config, start time.Time, tr *liveTracker, done <-chan struct{}) {
	if cfg.heartbeat <= 0 {
		return
	}
	t := time.NewTicker(cfg.heartbeat)
	defer t.Stop()
	for {
		select {
		case <-done:
			return
		case <-t.C:
			turns, tools, tokens, lines, last := tr.progress()
			parts := []string{humanDur(time.Since(start))}
			if tokens > 0 {
				// exec reports usage only at turn.completed, so tokens stay 0 within a
				// turn; review reports them late too. Show them once known, omit until.
				parts = append(parts, humanInt(tokens)+" tokens")
			}
			// turns is exec-only (review has no turn concept); tool-calls is the live
			// intra-turn progress signal in BOTH modes (exec command_execution items /
			// review `exec` markers) — show it always so the line moves before the first
			// turn completes.
			if cfg.mode == "exec" {
				parts = append(parts, plural(turns, "turn"))
			}
			parts = append(parts, plural(tools, "tool-call"))
			if last == "" {
				last = fmt.Sprintf("(%d trace lines, starting…)", lines)
			}
			fmt.Fprintf(os.Stderr, "  · [%s] codex working · %s\n",
				strings.Join(parts, " · "), clip(last, 120))
		}
	}
}

// plural renders "1 turn" / "2 turns" so the stats line reads naturally.
func plural(n int, noun string) string {
	if n == 1 {
		return "1 " + noun
	}
	return fmt.Sprintf("%d %ss", n, noun)
}

// humanInt renders a token count compactly: 18358 → "18.4k", 1500000 → "1.5M".
func humanInt(n int) string {
	switch {
	case n >= 1_000_000:
		return fmt.Sprintf("%.1fM", float64(n)/1e6)
	case n >= 1_000:
		return fmt.Sprintf("%.1fk", float64(n)/1e3)
	default:
		return strconv.Itoa(n)
	}
}

// numRE matches the first run of digits (with optional thousands separators).
var numRE = regexp.MustCompile(`[0-9][0-9,]*`)

// parseInt extracts the FIRST integer in s, tolerating thousands separators and trailing
// junk ("18,358" → 18358; "18,358 (cached: 4,992)" → 18358; "n/a" → 0). Returns 0 when
// there is no number, so a non-count line never corrupts the token total.
func parseInt(s string) int {
	m := numRE.FindString(s)
	if m == "" {
		return 0
	}
	n, err := strconv.Atoi(strings.ReplaceAll(m, ",", ""))
	if err != nil {
		return 0
	}
	return n
}

// firstLine returns the first non-empty line of s, trimmed — codex commands/messages
// can be multi-line; the heartbeat wants one.
func firstLine(s string) string {
	for _, ln := range strings.Split(s, "\n") {
		if ln = strings.TrimSpace(ln); ln != "" {
			return ln
		}
	}
	return ""
}

// clip truncates s to n runes with an ellipsis, never mid-rune.
func clip(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n]) + "…"
}

// hbLabel / verboseLabel render the start banner's mode bits.
func hbLabel(d time.Duration) string {
	if d <= 0 {
		return "off"
	}
	return d.String()
}

func verboseLabel(v bool) string {
	if v {
		return " · verbose"
	}
	return ""
}

func fail(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "codexreview: "+format+"\n", a...)
	os.Exit(1)
}
